# Generated by Django 4.1.2 on 2022-10-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_hlo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hlo',
        ),
    ]
